import { useEffect, useRef, useState } from 'react';
import { AlertTriangle, Camera, CheckCircle2, ImageUp, LoaderCircle, LogOut, RefreshCw, ScanLine, X } from 'lucide-react';
import { BrowserQRCodeReader } from '@zxing/browser';
import { api } from '../lib/api';
import { useAuth } from '../context/AuthContext';

const constraints = { audio: false, video: { facingMode: { ideal: 'environment' }, width: { ideal: 1280 }, height: { ideal: 720 } } };

export default function ScannerPage() {
  const { user, logout } = useAuth();
  const videoRef = useRef(null); const controlsRef = useRef(null); const busyRef = useRef(false);
  const readerRef = useRef(new BrowserQRCodeReader(undefined, { delayBetweenScanAttempts: 120, delayBetweenScanSuccess: 800 }));
  const [camera, setCamera] = useState('off'); const [result, setResult] = useState(null); const [error, setError] = useState(''); const [reading, setReading] = useState(false);
  function stop() { controlsRef.current?.stop(); controlsRef.current = null; videoRef.current?.srcObject?.getTracks?.().forEach((track) => track.stop()); if (videoRef.current) videoRef.current.srcObject = null; setCamera('off'); }
  async function submit(payload) { if (busyRef.current) return; busyRef.current = true; setError(''); try { const data = await api('/scans', { method: 'POST', body: JSON.stringify({ payload }) }); setResult(data); stop(); navigator.vibrate?.(data.firstScan ? 100 : [150, 80, 150]); } catch (e) { setError(e.message || 'QR could not be verified'); setTimeout(() => { busyRef.current = false; }, 1000); } }
  async function start() { setError(''); setCamera('starting'); busyRef.current = false; try { const controls = await readerRef.current.decodeFromConstraints(constraints, videoRef.current, (scanResult, _error, active) => { if (!scanResult || busyRef.current) return; active.stop(); submit(scanResult.getText()); }); controlsRef.current = controls; setCamera('on'); } catch { stop(); setError('Camera could not open. Allow camera permission or choose a QR image.'); } }
  async function scanImage(event) { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; stop(); setReading(true); setError(''); busyRef.current = false; const url = URL.createObjectURL(file); try { const found = await readerRef.current.decodeFromImageUrl(url); await submit(found.getText()); } catch { setError('No readable QR was found in this image.'); busyRef.current = false; } finally { URL.revokeObjectURL(url); setReading(false); } }
  function reset() { setResult(null); setError(''); busyRef.current = false; setTimeout(start, 0); }
  useEffect(() => () => stop(), []);
  const duplicate = result && !result.firstScan;
  return <main className={`min-h-[100dvh] ${duplicate ? 'bg-red-50' : result ? 'bg-emerald-50' : 'bg-slate-950'}`}>
    <header className="border-b border-white/10 bg-slate-950 px-4 py-3 text-white"><div className="mx-auto flex max-w-xl items-center justify-between"><div><div className="font-bold">GEHU Gate Entry</div><div className="text-xs text-slate-400">Freshers’ Party 2026 · {user.name}</div></div><button onClick={logout} className="flex h-10 items-center gap-2 rounded-lg border border-white/20 px-3 text-sm"><LogOut size={16}/>Sign out</button></div></header>
    <div className="mx-auto max-w-xl p-4 sm:py-7">{error ? <div className="mb-4 rounded-xl border border-red-300 bg-red-100 p-3 text-sm text-red-800">{error}</div> : null}
      {!result ? <section className="overflow-hidden rounded-3xl bg-white shadow-2xl"><div className="relative aspect-[4/5] overflow-hidden bg-slate-900"><video ref={videoRef} playsInline muted className="h-full w-full object-cover"/>{camera !== 'on' ? <div className="absolute inset-0 flex flex-col items-center justify-center gap-4 text-white"><Camera size={48}/><h1 className="text-xl font-bold">Scan gate pass</h1><button onClick={start} disabled={camera === 'starting'} className="flex h-12 items-center gap-2 rounded-xl bg-fuchsia-600 px-6 font-semibold">{camera === 'starting' ? <LoaderCircle className="animate-spin"/> : <Camera/>}{camera === 'starting' ? 'Opening…' : 'Open camera'}</button></div> : <><div className="pointer-events-none absolute left-1/2 top-1/2 aspect-square w-[70%] -translate-x-1/2 -translate-y-1/2 rounded-3xl border-4 border-fuchsia-400 shadow-[0_0_0_999px_rgba(2,6,23,.55)]"/><div className="absolute bottom-6 left-0 right-0 flex justify-center"><span className="flex items-center gap-2 rounded-full bg-black/70 px-4 py-2 text-sm text-white"><ScanLine size={18}/>Fit QR inside the box</span></div></>}</div><div className="grid gap-2 p-3 sm:grid-cols-2"><button onClick={camera === 'on' ? stop : start} className="flex h-12 items-center justify-center gap-2 rounded-xl border font-semibold">{camera === 'on' ? <X/> : <Camera/>}{camera === 'on' ? 'Stop camera' : 'Start camera'}</button><label className="flex h-12 cursor-pointer items-center justify-center gap-2 rounded-xl bg-fuchsia-600 font-semibold text-white">{reading ? <LoaderCircle className="animate-spin"/> : <ImageUp/>}{reading ? 'Reading…' : 'Choose QR image'}<input className="sr-only" type="file" accept="image/*" onChange={scanImage}/></label></div></section>
      : <section className={`overflow-hidden rounded-3xl border-2 bg-white shadow-2xl ${duplicate ? 'border-red-500' : 'border-emerald-500'}`}><div className={`p-7 text-center text-white ${duplicate ? 'bg-red-600' : 'bg-emerald-600'}`}>{duplicate ? <AlertTriangle className="mx-auto" size={64}/> : <CheckCircle2 className="mx-auto" size={64}/>}<h1 className="mt-3 text-3xl font-black">{duplicate ? 'ALREADY SCANNED' : 'ENTRY SUCCESSFUL'}</h1><p className="mt-1 text-sm opacity-90">{duplicate ? 'This gate pass has already been used.' : 'Student may enter the event.'}</p></div><dl className="divide-y p-5">{[['Student name', result.student.name], ['Student ID', result.student.studentId]].map(([label, value]) => <div key={label} className="py-4 text-center"><dt className="text-xs font-bold uppercase tracking-wider text-slate-400">{label}</dt><dd className="mt-1 text-xl font-bold text-slate-900">{value}</dd></div>)}</dl><div className="p-4 pt-0"><button onClick={reset} className={`flex h-14 w-full items-center justify-center gap-2 rounded-xl text-lg font-bold text-white ${duplicate ? 'bg-red-600' : 'bg-emerald-600'}`}><RefreshCw/>Scan next student</button></div></section>}
    </div>
  </main>;
}
