import { useEffect, useState } from 'react';
import { CheckCircle2, FileSpreadsheet, Upload } from 'lucide-react';
import { api } from '../lib/api';

export default function StudentDataUploadPage() {
  const [status,setStatus]=useState(null); const [file,setFile]=useState(null); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [working,setWorking]=useState(false);
  const load=()=>api('/student-data/status').then(setStatus).catch(e=>setError(e.message)); useEffect(load,[]);
  async function submit(e){e.preventDefault();if(!file)return setError('Choose the mapping Excel file from the QR ZIP');setWorking(true);setError('');setNotice('');const body=new FormData();body.append('file',file);try{const data=await api('/student-data/upload',{method:'POST',body});setNotice(`${data.updated} student QR links updated successfully.`);setFile(null);load()}catch(err){setError(err.message)}finally{setWorking(false)}}
  return <div className="space-y-5"><div><h1 className="text-2xl font-bold">Student Data Upload</h1><p className="mt-1 text-sm text-slate-500">Upload the QR mapping Excel after the JPG passes have been uploaded to files.geu.ac.in.</p></div><div className="grid gap-4 sm:grid-cols-3">{[['Total students',status?.total],['S3 links mapped',status?.linked],['Waiting for mapping',status?.pending]].map(([label,value])=><div key={label} className="rounded-2xl border bg-white p-5"><div className="text-sm text-slate-500">{label}</div><div className="mt-2 text-3xl font-black">{value??'—'}</div></div>)}</div>{error?<div className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>:null}{notice?<div className="flex items-center gap-2 rounded-xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-700"><CheckCircle2 size={18}/>{notice}</div>:null}<form onSubmit={submit} className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex items-start gap-4"><div className="rounded-xl bg-emerald-100 p-3 text-emerald-700"><FileSpreadsheet/></div><div><h2 className="font-bold">Upload QR mapping</h2><p className="mt-1 text-sm text-slate-500">Use the students.xlsx file included in the downloaded QR ZIP. Links must begin with https://files.geu.ac.in/induction/btech12/.</p></div></div><label className="mt-6 flex min-h-32 cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-slate-300 bg-slate-50 p-5 text-center hover:border-fuchsia-400"><Upload className="text-slate-400"/><span className="mt-2 font-semibold">{file?.name||'Choose Excel or CSV file'}</span><input type="file" accept=".xlsx,.csv" className="sr-only" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button disabled={!file||working} className="mt-4 h-12 w-full rounded-xl bg-fuchsia-600 font-bold text-white disabled:opacity-40">{working?'Uploading…':'Upload and map student links'}</button></form></div>;
}
