import { useEffect, useState } from 'react';
import { Download, KeyRound, LogOut, Phone, QrCode } from 'lucide-react';
import { api } from '../lib/api';

const storageKey = 'gehu_gate_pass_student';
export default function StudentLoginPage() {
  const [step,setStep]=useState('mobile'); const [mobile,setMobile]=useState(''); const [otp,setOtp]=useState(''); const [student,setStudent]=useState(null); const [testOtp,setTestOtp]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
  useEffect(()=>{try{const saved=localStorage.getItem(storageKey);if(saved)setStudent(JSON.parse(saved))}catch{localStorage.removeItem(storageKey)}},[]);
  async function requestOtp(e){e.preventDefault();setLoading(true);setError('');setTestOtp('');try{const data=await api('/student-auth/request-otp',{method:'POST',body:JSON.stringify({mobile})});setTestOtp(data.otp||'');setStep('otp')}catch(err){setError(err.message)}finally{setLoading(false)}}
  async function verifyOtp(e){e.preventDefault();setLoading(true);setError('');try{const data=await api('/student-auth/verify-otp',{method:'POST',body:JSON.stringify({mobile,otp})});setStudent(data.student);localStorage.setItem(storageKey,JSON.stringify(data.student))}catch(err){setError(err.message)}finally{setLoading(false)}}
  function logout(){localStorage.removeItem(storageKey);setStudent(null);setOtp('');setStep('mobile')}
  if(student)return <main className="min-h-screen bg-slate-950 p-4 sm:py-8"><section className="mx-auto max-w-md overflow-hidden rounded-3xl bg-white shadow-2xl"><div className="bg-gradient-to-r from-fuchsia-700 to-purple-700 p-6 text-white"><div className="flex justify-between gap-3"><div><div className="text-xs font-bold uppercase tracking-[.25em] text-fuchsia-200">Your gate pass</div><h1 className="mt-2 text-2xl font-black">{student.name}</h1><p className="mt-1 text-sm text-fuchsia-100">{student.studentId} · Semester {student.semester}</p></div><button onClick={logout} title="Sign out" className="h-10 rounded-xl bg-white/15 p-2"><LogOut/></button></div></div><div className="p-5"><div className="overflow-hidden rounded-2xl border bg-slate-50"><img src={student.qrLink} alt={`${student.name} gate pass`} className="w-full"/></div><a href={student.qrLink} download={`${student.studentId}-gate-pass.jpg`} className="mt-4 flex h-12 items-center justify-center gap-2 rounded-xl bg-fuchsia-600 font-bold text-white"><Download size={19}/>Download gate pass</a><p className="mt-3 text-center text-xs text-slate-500">Show this QR at the entry gate. It allows one successful entry only.</p></div></section></main>;
  return <main className="flex min-h-screen items-center justify-center bg-slate-950 p-4"><section className="w-full max-w-sm rounded-3xl bg-white p-6 shadow-2xl"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-fuchsia-100 text-fuchsia-700"><QrCode size={30}/></div><h1 className="mt-5 text-center text-2xl font-black">Get your gate pass</h1><p className="mt-2 text-center text-sm text-slate-500">{step==='mobile'?'Enter your registered mobile number.':'Enter the 4-digit OTP sent to your mobile.'}</p>{error?<div className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>:null}{step==='mobile'?<form onSubmit={requestOtp} className="mt-5 space-y-4"><label className="block"><span className="text-xs font-bold text-slate-700">Registered mobile number</span><div className="relative mt-1.5"><Phone className="absolute left-3 top-3 text-slate-400" size={18}/><input required inputMode="tel" value={mobile} onChange={e=>setMobile(e.target.value)} className="h-11 w-full rounded-xl border pl-10 pr-3" placeholder="Enter mobile number"/></div></label><button disabled={loading} className="h-12 w-full rounded-xl bg-fuchsia-600 font-bold text-white disabled:opacity-50">{loading?'Sending OTP…':'Send 4-digit OTP'}</button></form>:<form onSubmit={verifyOtp} className="mt-5 space-y-4">{testOtp?<div className="rounded-xl bg-blue-50 p-3 text-center text-sm text-blue-700">Test OTP: <b>{testOtp}</b></div>:null}<label className="block"><span className="text-xs font-bold text-slate-700">4-digit OTP</span><div className="relative mt-1.5"><KeyRound className="absolute left-3 top-3 text-slate-400" size={18}/><input required autoFocus inputMode="numeric" maxLength={4} value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,'').slice(0,4))} className="h-12 w-full rounded-xl border pl-10 pr-3 text-center text-xl font-bold tracking-[.5em]" placeholder="0000"/></div></label><button disabled={loading||otp.length!==4} className="h-12 w-full rounded-xl bg-fuchsia-600 font-bold text-white disabled:opacity-50">{loading?'Verifying…':'Verify and show pass'}</button><button type="button" onClick={()=>{setStep('mobile');setOtp('');setError('')}} className="h-10 w-full rounded-xl border font-semibold text-slate-600">Change mobile number</button></form>}<a href="/admin" className="mt-5 block text-center text-xs font-semibold text-slate-500">Admin / scan coordinator login</a></section></main>;
}
