import { useEffect, useState } from 'react';
import { Download, LogOut, Phone, QrCode } from 'lucide-react';
import { api } from '../lib/api';

const storageKey = 'gehu_gate_pass_student';
export default function StudentLoginPage() {
  const [mobile,setMobile]=useState(''); const [student,setStudent]=useState(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
  useEffect(()=>{try{const saved=localStorage.getItem(storageKey);if(saved)setStudent(JSON.parse(saved))}catch{localStorage.removeItem(storageKey)}},[]);
  async function login(e){e.preventDefault();setLoading(true);setError('');try{const data=await api('/student-auth/login',{method:'POST',body:JSON.stringify({mobile})});setStudent(data.student);localStorage.setItem(storageKey,JSON.stringify(data.student))}catch(err){setError(err.message)}finally{setLoading(false)}}
  function logout(){localStorage.removeItem(storageKey);setStudent(null)}
  if(student)return <main className="min-h-screen bg-slate-950 p-4 sm:py-8"><section className="mx-auto max-w-md overflow-hidden rounded-3xl bg-white shadow-2xl"><div className="bg-gradient-to-r from-fuchsia-700 to-purple-700 p-6 text-white"><div className="flex justify-between gap-3"><div><div className="text-xs font-bold uppercase tracking-[.25em] text-fuchsia-200">Your gate pass</div><h1 className="mt-2 text-2xl font-black">{student.name}</h1><p className="mt-1 text-sm text-fuchsia-100">{student.studentId} · Semester {student.semester}</p></div><button onClick={logout} title="Sign out" className="h-10 rounded-xl bg-white/15 p-2"><LogOut/></button></div></div><div className="p-5"><div className="overflow-hidden rounded-2xl border bg-slate-50"><img src={student.qrLink} alt={`${student.name} gate pass`} className="w-full"/></div><a href={student.qrLink} download={`${student.studentId}-gate-pass.svg`} className="mt-4 flex h-12 items-center justify-center gap-2 rounded-xl bg-fuchsia-600 font-bold text-white"><Download size={19}/>Download gate pass</a><p className="mt-3 text-center text-xs text-slate-500">Show this QR at the entry gate. It allows one successful entry only.</p></div></section></main>;
  return <main className="flex min-h-screen items-center justify-center bg-slate-950 p-4"><section className="w-full max-w-sm rounded-3xl bg-white p-6 shadow-2xl"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-fuchsia-100 text-fuchsia-700"><QrCode size={30}/></div><h1 className="mt-5 text-center text-2xl font-black">Get your gate pass</h1><p className="mt-2 text-center text-sm text-slate-500">Enter the mobile number registered by the administrator.</p>{error?<div className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>:null}<form onSubmit={login} className="mt-5 space-y-4"><label className="block"><span className="text-xs font-bold text-slate-700">Registered mobile number</span><div className="relative mt-1.5"><Phone className="absolute left-3 top-3 text-slate-400" size={18}/><input required inputMode="tel" value={mobile} onChange={e=>setMobile(e.target.value)} className="h-11 w-full rounded-xl border pl-10 pr-3" placeholder="Enter mobile number"/></div></label><button disabled={loading} className="h-12 w-full rounded-xl bg-fuchsia-600 font-bold text-white disabled:opacity-50">{loading?'Checking…':'Show my gate pass'}</button></form><a href="/admin" className="mt-5 block text-center text-xs font-semibold text-slate-500">Admin / scan coordinator login</a></section></main>;
}
