import { useEffect, useState } from 'react';
import { CheckCircle2, Database, LayoutDashboard, LogOut, ScanLine, UserRound, Users } from 'lucide-react';
import { useAuth } from './context/AuthContext';
import { api } from './lib/api';
import LoginPage from './pages/LoginPage';
import StudentsPage from './pages/StudentsPage';
import CoordinatorsPage from './pages/CoordinatorsPage';
import ScannerPage from './pages/ScannerPage';
import StudentLoginPage from './pages/StudentLoginPage';
import StudentDataUploadPage from './pages/StudentDataUploadPage';

const nav = [['Dashboard',LayoutDashboard],['Students',Users],['Student Data Upload',Database],['Scan Coordinators',UserRound]];
function Stat({label,value,icon:Icon,tone='slate'}){const colors={slate:'bg-slate-100 text-slate-700',green:'bg-emerald-100 text-emerald-700',amber:'bg-amber-100 text-amber-700',pink:'bg-fuchsia-100 text-fuchsia-700'};return <div className="rounded-2xl border bg-white p-5 shadow-sm"><div className={`inline-flex rounded-xl p-2 ${colors[tone]}`}><Icon size={20}/></div><div className="mt-4 text-3xl font-black">{value??'—'}</div><div className="mt-1 text-sm text-slate-500">{label}</div></div>}
function Dashboard(){const [data,setData]=useState(null);useEffect(()=>{api('/dashboard/admin').then(setData)},[]);const c=data?.counts||{};return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Gate entry dashboard</h1><p className="text-sm text-slate-500">Live overview for Freshers’ Party 2026.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><Stat label="Total students" value={c.totalStudents} icon={Users}/><Stat label="Successfully entered" value={c.enteredStudents} icon={CheckCircle2} tone="green"/><Stat label="Waiting for entry" value={c.waitingStudents} icon={ScanLine} tone="amber"/><Stat label="Entries today" value={c.scansToday} icon={ScanLine} tone="pink"/><Stat label="Duplicate scan attempts" value={c.duplicateScansToday} icon={ScanLine}/><Stat label="Active scan coordinators" value={c.scanCoordinators} icon={UserRound}/></div><div className="rounded-2xl border bg-white p-6"><div className="flex justify-between"><b>Entry progress</b><b className="text-fuchsia-700">{data?.entryPercent||0}%</b></div><div className="mt-4 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-fuchsia-600 to-purple-600" style={{width:`${data?.entryPercent||0}%`}}/></div></div></div>}
function Admin(){const {user,logout}=useAuth();const [page,setPage]=useState('Dashboard');return <div className="min-h-screen bg-slate-50"><aside className="fixed inset-y-0 hidden w-64 bg-slate-950 text-white lg:block"><div className="border-b border-white/10 p-6"><div className="text-lg font-black">GEHU Gate Entry</div><div className="mt-1 text-xs text-fuchsia-300">Freshers’ Party 2026</div></div><nav className="space-y-1 p-3">{nav.map(([label,Icon])=><button key={label} onClick={()=>setPage(label)} className={`flex w-full items-center gap-3 rounded-xl px-4 py-3 text-sm font-semibold ${page===label?'bg-fuchsia-600':'text-slate-300 hover:bg-white/10'}`}><Icon size={18}/>{label}</button>)}</nav><button onClick={logout} className="absolute bottom-4 left-4 right-4 flex items-center gap-3 rounded-xl px-4 py-3 text-sm text-slate-300 hover:bg-white/10"><LogOut size={18}/>Sign out</button></aside><main className="lg:pl-64"><header className="sticky top-0 z-30 flex items-center justify-between border-b bg-white/95 px-4 py-3 backdrop-blur lg:px-8"><select value={page} onChange={e=>setPage(e.target.value)} className="h-10 rounded-lg border px-3 lg:hidden">{nav.map(([label])=><option key={label}>{label}</option>)}</select><div className="hidden font-semibold lg:block">{page}</div><div className="text-right"><div className="text-sm font-bold">{user.name}</div><div className="text-xs text-slate-500">Administrator</div></div></header><div className="p-4 sm:p-6 lg:p-8">{page==='Students'?<StudentsPage/>:page==='Student Data Upload'?<StudentDataUploadPage/>:page==='Scan Coordinators'?<CoordinatorsPage/>:<Dashboard/>}</div></main></div>}
export default function App(){const {user,loading}=useAuth();const path=window.location.pathname.replace(/\/+$/,'')||'/';const staff=path==='/admin'||path==='/link/new/every/admin';if(loading)return <div className="grid min-h-screen place-items-center">Loading…</div>;if(!staff)return <StudentLoginPage/>;if(!user)return <LoginPage/>;if(user.role==='scan_coordinator')return <ScannerPage/>;if(user.role==='admin')return <Admin/>;return null}
